## PyTorch Fundamentals

### PyTorch Tensors 

In [48]:
import torch

In [49]:
X = torch.tensor(
    [
        [1.0, 4.0, 7.0],
        [2.0, 3.0, 6.0]
    ],
)

In [50]:
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [51]:
print(X.shape)
print(X.dtype)

torch.Size([2, 3])
torch.float32


In [52]:
print(X[0, 1])
print(X[:,1])

tensor(4.)
tensor([4., 3.])


In [53]:
10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [54]:
print(X.exp())
print(X.mean())
print(X.max(dim=0)) # note: dim 0 means across dim 0 i.e. across rows i.e. max of all the cols

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])
tensor(3.8333)
torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))


In [33]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

Converting a tensor into a numpy array.

In [34]:
import numpy as np
X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [35]:
torch.tensor(np.array(
    [
        [1.0, 4.0, 7.0],
        [2.0, 3.0, 6.0]
    ]
))

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

The default precision for floats is 32 bits in PyTorch, whereas it’s 64 bits in NumPy. It’s generally better to use 32 bits in deep learning. So when calling the torch.tensor() function
to convert a NumPy array to a tensor, it’s best to specify dtype=torch.float32.

In [36]:
torch.tensor(np.array(
    [
        [1.0, 4.0, 7.0],
        [2.0, 3.0, 6.0]
    ]
), dtype=torch.float32)

tensor([[1., 4., 7.],
        [2., 3., 6.]])

You can also modify a tensor in place using indexing and slicing, as with a NumPy array.

In [37]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In-place operations: abs_(), sqrt_(), zero_(), relu_()  
Regular operations: abs(), sqrt(), zero(), relu()

In [38]:
X.abs_()
X

tensor([[ 1., 99.,  7.],
        [ 2., 99.,  6.]])

### Hardware Acceleration


In [55]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_properties(0))

True
1
0
NVIDIA GeForce RTX 4060 Laptop GPU
_CudaDeviceProperties(name='NVIDIA GeForce RTX 4060 Laptop GPU', major=8, minor=9, total_memory=8187MB, multi_processor_count=24, uuid=a682ab30-74b5-8cfa-b6d0-884254cbea06, pci_bus_id=1, pci_device_id=0, pci_domain_id=0, L2_cache_size=32MB)


In [56]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

device

'cuda'

Lets create a tensor on the GPU. One option is to create tensor on the CPU and then copy it to the GPU using the to() method.


In [57]:
M = torch.tensor(
    [
        [1., 2., 3.],
        [4., 5., 6.]
    ]
)
M = M.to(device)

M.device

device(type='cuda', index=0)

Another option is to create tensor directly on the GPU using device argument.


In [59]:
M = torch.tensor(
    [
        [1., 2., 3.],
        [4., 5., 6.]
    ], 
    device=device
)

M.device

device(type='cuda', index=0)

Once the tensor is on the GPU, we can run operations on it normally, and they will all take place on the GPU:

In [60]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

Let’s run a little test to compare the speed of a matrix multiplication running on the CPU versus the GPU.

In [85]:
M = torch.rand((1000, 1000))
%timeit M @ M.T

8.38 ms ± 426 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [86]:
M = torch.rand((1000, 1000), device=device)
%timeit M @ M.T

319 μs ± 6.49 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


GPU gave around 25 times than the CPU.

## Autograd