## PyTorch Fundamentals

### PyTorch Tensors 

In [48]:
import torch

In [49]:
X = torch.tensor(
    [
        [1.0, 4.0, 7.0],
        [2.0, 3.0, 6.0]
    ],
)

In [50]:
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [51]:
print(X.shape)
print(X.dtype)

torch.Size([2, 3])
torch.float32


In [52]:
print(X[0, 1])
print(X[:,1])

tensor(4.)
tensor([4., 3.])


In [53]:
10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [54]:
print(X.exp())
print(X.mean())
print(X.max(dim=0)) # note: dim 0 means across dim 0 i.e. across rows i.e. max of all the cols

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])
tensor(3.8333)
torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))


In [33]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

Converting a tensor into a numpy array.

In [34]:
import numpy as np
X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [35]:
torch.tensor(np.array(
    [
        [1.0, 4.0, 7.0],
        [2.0, 3.0, 6.0]
    ]
))

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

The default precision for floats is 32 bits in PyTorch, whereas it’s 64 bits in NumPy. It’s generally better to use 32 bits in deep learning. So when calling the torch.tensor() function
to convert a NumPy array to a tensor, it’s best to specify dtype=torch.float32.

In [36]:
torch.tensor(np.array(
    [
        [1.0, 4.0, 7.0],
        [2.0, 3.0, 6.0]
    ]
), dtype=torch.float32)

tensor([[1., 4., 7.],
        [2., 3., 6.]])

You can also modify a tensor in place using indexing and slicing, as with a NumPy array.

In [37]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In-place operations: abs_(), sqrt_(), zero_(), relu_()  
Regular operations: abs(), sqrt(), zero(), relu()

In [38]:
X.abs_()
X

tensor([[ 1., 99.,  7.],
        [ 2., 99.,  6.]])