# PCA

## Principle Components

So how can you find the principal components of a training set? Luckily, there is
a standard matrix factorization technique called singular value decomposition (SVD)
that can decompose the training set matrix X into the matrix multiplication of three
matrices U Σ V⊺, where V contains the unit vectors that define all the principal
components that you are looking for, in the correct order.

In [1]:
import numpy as np

X = np.random.randint(1, 9, (5, 3))
X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt[0]
c2 = Vt[1]

In [2]:
c1, c2

(array([-0.37830527,  0.81393178, -0.44090837]),
 array([ 0.77522413,  0.01827198, -0.63142195]))

Projecting down to d dimensions  
The following Python code projects the training set onto the plane defined by the first
two principal components:

In [3]:
W2 = Vt[:2].T
X2D = X_centered @ W2

In [4]:
X2D

array([[-2.15697189,  2.85937511],
       [-2.22485685,  1.61480318],
       [ 5.49467998,  0.51780443],
       [ 1.73544141, -1.59335154],
       [-2.84829266, -3.39863118]])