# PCA

## Principle Components

So how can you find the principal components of a training set? Luckily, there is
a standard matrix factorization technique called singular value decomposition (SVD)
that can decompose the training set matrix X into the matrix multiplication of three
matrices U Σ V⊺, where V contains the unit vectors that define all the principal
components that you are looking for, in the correct order.

In [11]:
import numpy as np

# X = np.random.randint(1, 9, (5, 3))
X = np.array([
    [2, 5, 6],
    [3, 2, 2],
    [5, 1, 9],
    [3, 9, 8],
    [3, 2, 4]
])
X_centered = X - X.mean(axis=0)

X_centered

array([[-1.2,  1.2,  0.2],
       [-0.2, -1.8, -3.8],
       [ 1.8, -2.8,  3.2],
       [-0.2,  5.2,  2.2],
       [-0.2, -1.8, -1.8]])

In [12]:
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt[0]
c2 = Vt[1]
c1, c2

(array([ 0.04815873, -0.83354534, -0.55034799]),
 array([-0.36344149,  0.49859498, -0.78696463]))

## Projecting down to d dimensions  
The following Python code projects the training set onto the plane defined by the first
two principal components:

In [5]:
W2 = Vt[:2].T
X2D = X_centered @ W2

In [6]:
X2D

array([[-2.15697189,  2.85937511],
       [-2.22485685,  1.61480318],
       [ 5.49467998,  0.51780443],
       [ 1.73544141, -1.59335154],
       [-2.84829266, -3.39863118]])

## Using Sklearn

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X2D = pca.fit_transform(X)

## Explained Variance Ratio